spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
  h2:
    console:
      enabled: true
      path: /h2-console

data:
  messages:
    page:
      limit: 5
